site_name: Key Management System
site_url: https://example.com/
site_author: Godbless Nyagawa
site_description: Documentation for the Key Management System.
repo_url: https://github.com/Njoxpy/key-management-system
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: "#FF6F00"  # Orange (Primary color)
      accent: "#00897B"   # Teal (Secondary/Accent color)
      background: "#FFFFFF"  # White background for light mode
      text: "#000000"  # Black text for light mode

    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: "#FF6F00"  # Orange (Primary color)
      accent: "#00897B"   # Teal (Secondary/Accent color)
      background: "#121212"  # Dark background for dark mode
      text: "#FFFFFF"  # White text for dark mode

  font:
    text: Roboto  # Primary font for text content
    code: Roboto Mono  # Font for code blocks
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - System Design:
    - Functional requirements: system design\functional-requirements.md
    - Non-Functional requirements(NFRs): system design\non-functional-requirements.md
    - High Level Design:
        - Database Design: system design\database-design.md
        - Flow Diagram: system design\flow-diagram.md
        - UML Diagrams: uml/uml.md
    - API Reference:
        - Overview: api/api.md
        - Logs: api/logs.md
        - Orders: api/orders.md
        - Users: api/user.md
        - Venues: api/venue.md
  - Frontend:
      - Styles:
          - Colors: styles\colors.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Njoxpy/key-management-system
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Njox16

  # Optional: Set logo and favicon
  logo: assets/logo.png
  favicon: assets/favicon.ico